name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master]

jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./FlashcardsAPI

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

  build-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./FlashcardsUI

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./FlashcardsUI/.nvmrc
          cache-dependency-path: "./FlashcardsUI/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
